networks:
  internet:
  local:
    name: ${PREFIX}nitrotype-tracker-local-internal
    internal: true
  public:
    name: tyr-proxy-internal
    driver: overlay
    external: true
  infra:
    name: tyr-infrastructure-internal
    driver: overlay
    external: true
  admin:
    name: tyr-administration-internal
    driver: overlay
    external: true

services:
  api:
    image: ghcr.io/ewancoder/nitrotype-tracker-api:${API_TAG}
    container_name: ${PREFIX}nitrotype-tracker-api
    volumes:
      - /data/${VOLUME_ROOT}/dataprotection:/app/dataprotection
      - /root/dp.pfx:/app/dp.pfx
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - /data/${VOLUME_ROOT}/secrets.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - local
      - public
      - infra

  be-fetch:
    image: ghcr.io/ewancoder/nitrotype-tracker-be-fetch:${BE_FETCH_TAG}
    #container_name: ${PREFIX}nitrotype-tracker-be-fetch
    restart: unless-stopped
    mem_limit: 100m
    mem_reservation: 75m
    env_file:
      - /data/${VOLUME_ROOT}/secrets.env
    depends_on:
      postgres:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - local
      - infra
      - internet
    deploy:
      replicas: ${BE_FETCH_REPLICAS}

  postgres:
    image: postgres:17
    container_name: ${PREFIX}nitrotype-tracker-postgres
    volumes:
      - /data/${VOLUME_ROOT}/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - /data/${VOLUME_ROOT}/secrets.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - local
      #- admin    # Disabled in production until needed.
      #- internet # Needed for development env to expose ports to host.

  cache:
    image: valkey/valkey
    container_name: ${PREFIX}nitrotype-tracker-cache
    command: valkey-server --save 60 1
    restart: unless-stopped
    ports:
      - ${CACHE_PORT}
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - /data/${VOLUME_ROOT}/secrets.env
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - local
      #- admin    # Disabled in production until needed.
      #- internet # Needed for development env to expose ports to host.

  web:
    image: ghcr.io/ewancoder/nitrotype-tracker-web:${WEB_TAG}
    #container_name: ${PREFIX}nitrotype-tracker-web
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    networks:
      - public
    deploy:
      replicas: ${WEB_REPLICAS}
