name: test-go-sonarqube
inputs:
  sonarToken:
    description: Sonar secret token
    required: true
  folder:
    description: Source code base folder
    required: true
permissions:
  contents: read
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ inputs.sonarToken }}
      with:
        projectBaseDir: ${{ inputs.folder }}
