name: Deploy

on:
  push:
    branches:
      - 'main'
      - 'develop'

env:
  REGISTRY: ghcr.io
  API_IMAGE: nitrotype-tracker-api
  API_DOCKERFILE: backend/NitroType.Tracker.Api/Dockerfile
  WEB_UI_DOCKERFILE: frontend/Dockerfile
  WEB_UI_IMAGE: nitrotype-tracker-web

jobs:
  build-api:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.filter-backend.outputs.backend }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if backend files changed
        id: filter-backend
        run: |
          BEFORE_SHA="${{ github.event.before }}"
          if [ "$BEFORE_SHA" == "0000000000000000000000000000000000000000" ] || [ -z "$BEFORE_SHA" ]; then
            echo "First time push"
            echo "backend=true" >> $GITHUB_OUTPUT
          elif git diff --name-only $BEFORE_SHA HEAD | grep -q '^backend/'; then
            echo "Backend files changed"
            echo "backend=true" >> $GITHUB_OUTPUT
          else
            echo "backend=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to GitHub Container registry
        if: steps.filter-backend.outputs.backend == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        if: steps.filter-backend.outputs.backend == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/ewancoder/${{ env.API_IMAGE }}

      - name: Build and push Docker image
        if: steps.filter-backend.outputs.backend == 'true'
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          file: ${{ env.API_DOCKERFILE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-web-ui:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter-frontend.outputs.frontend }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if frontend files changed
        id: filter-frontend
        run: |
          BEFORE_SHA="${{ github.event.before }}"
          if [ "$BEFORE_SHA" == "0000000000000000000000000000000000000000" ] || [ -z "$BEFORE_SHA" ]; then
            echo "First time push"
            echo "frontend=true" >> $GITHUB_OUTPUT
          elif git diff --name-only $BEFORE_SHA HEAD | grep -q '^frontend/'; then
            echo "Frontend files changed"
            echo "frontend=true" >> $GITHUB_OUTPUT
          else
            echo "frontend=false" >> $GITHUB_OUTPUT
          fi

      - name: Set CONFIG_FILE
        id: set-config
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "CONFIG_FILE=config.production.ts" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "CONFIG_FILE=config.development.ts" >> $GITHUB_ENV
          fi

      - name: Login to GitHub Container registry
        if: steps.filter-frontend.outputs.frontend == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        if: steps.filter-frontend.outputs.frontend == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/ewancoder/${{ env.WEB_UI_IMAGE }}

      - name: Build and push Docker image
        if: steps.filter-frontend.outputs.frontend == 'true'
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./frontend
          file: ${{ env.WEB_UI_DOCKERFILE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CONFIG_FILE=${{ env.CONFIG_FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build-api, build-web-ui]
    if: github.ref == 'refs/heads/main' && (needs.build-api.outputs.backend_changed == 'true' || needs.build-web-ui.outputs.frontend_changed == 'true')

    permissions:
      contents: read

    steps:
      - name: Deploy to DO
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            curl https://raw.githubusercontent.com/ewancoder/nitrotype-tracker/main/docker-compose-production.yml > /tmp/nitrotype-tracker-docker-compose.yml
            docker compose -f /tmp/nitrotype-tracker-docker-compose.yml pull
            docker compose -f /tmp/nitrotype-tracker-docker-compose.yml up -d
