name: Deploy

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  API_IMAGE: nitrotype-tracker-api
  API_DOCKERFILE: backend/NitroType.Tracker.Api/Dockerfile
  WEB_UI_DOCKERFILE: frontend/Dockerfile
  WEB_UI_IMAGE: nitrotype-tracker-web

jobs:
  build-api:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/ewancoder/${{ env.API_IMAGE }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          file: ${{ env.API_DOCKERFILE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-web-ui:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/ewancoder/${{ env.WEB_UI_IMAGE }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./frontend
          file: ${{ env.WEB_UI_DOCKERFILE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build-api, build-web-ui]

    permissions:
      contents: read

    steps:
      - name: Deploy to DO
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            curl https://raw.githubusercontent.com/ewancoder/nitrotype-tracker/main/docker-compose-production.yml > /tmp/nitrotype-tracker-docker-compose.yml
            docker compose -f /tmp/nitrotype-tracker-docker-compose.yml pull
            docker compose -f /tmp/nitrotype-tracker-docker-compose.yml up -d
